Retrieving revision 3402 of LineStretchContainerGlyph.java.
File was deleted in revision 3403.

This file is needed to compile com.affymetrix.igb.tiers.TestLabelledTier2:

init:
deps-jar:
Compiling 100 source files to /Users/admin/NetBeansProjects/IGBproject/build/classes
/Users/admin/src/genoviz/igb/test/com/affymetrix/igb/tiers/TestLabelledTier2.java:128: cannot find symbol
symbol  : class LineStretchContainerGlyph
location: class com.affymetrix.igb.tiers.TestLabelledTier2
      container = new LineStretchContainerGlyph();
...
1 error
BUILD FAILED (total time: 0 seconds)




git-svn-id: http://svn.code.sf.net/p/genoviz/code/trunk@3418 80d5a9c2-7d8c-4c9f-9369-4e03bca4d2bd