Fixed one compile error on NeoTracerDemo.java that broke the build on demos (tutorials) code, dating (I think?) from a merge with branch java_1_5.
    [javac] Compiling 44 source files to /afs/transvar.org/home/aloraine/genoviz/genoviz_sdk
    [javac] /afs/transvar.org/home/aloraine/genoviz/genoviz_sdk/demo/genoviz/NeoTracerDemo.java:81: cannot find symbol
    [javac] symbol  : method getBaseString()
    [javac] location: interface com.affymetrix.genoviz.datamodel.TraceI
    [javac]         traceString = trace.getBaseString();
    [javac]                            ^
    [javac] /afs/transvar.org/home/aloraine/genoviz/genoviz_sdk/demo/genoviz/NeoTracerDemo.java:511: cannot find symbol
    [javac] symbol  : method getBaseCall(int)
    [javac] location: interface com.affymetrix.genoviz.datamodel.TraceI
    [javac]       int a = (trace.getBaseCall(theFirstBase-1)).getTracePoint();


      BaseCalls bc = ( ( Trace ) trace ).getActiveBaseCalls();
      // Ann's note:getBaseString is
      // removed from v. 6
      // See: http://genoviz.svn.sourceforge.net/viewvc/genoviz/trunk/genoviz_sdk/src/com/affymetrix/genoviz/datamodel/TraceI.java?r1=6&r2=2846
      // The method was also noted as being deprecated and 
      // the comments advised using getActiveBaseCalls().getBaseString()
      // instead. 
      // 
      /**
         
      if ( null == bc ) {
        traceString = trace.getBaseString();
      }
      else {
      */
      traceString = bc.getBaseString().toUpperCase();
        //}

The 



git-svn-id: http://svn.code.sf.net/p/genoviz/code/trunk@3222 80d5a9c2-7d8c-4c9f-9369-4e03bca4d2bd